# FIXME Install moto
[tool.pytest.ini_options]
addopts = """
    --testmon
    --ignore tests/adapters/test_match_request_queues.py
    --ignore tests/adapters/test_game_repositories.py
"""

[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true
exclude_lines = [
    'def __repr__',
    '\s\.\.\.$'
]
