version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "paper-tactics"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-kf87s5gz04zs"
s3_prefix = "paper-tactics"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
