Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.9
    CodeUri: lambda-handlers/
    MemorySize: 128
    Architectures:
      - arm64

Resources:
  WebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: paper-tactics-api
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action

  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - CreateGameRoute
    Properties:
      ApiId: !Ref WebSocketApi

  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: rolling
      DeploymentId: !Ref Deployment
      ApiId: !Ref WebSocketApi
      AutoDeploy: true

  ClientQueueTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: paper-tactics-client-queue
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: connection-id
          AttributeType: S
      KeySchema:
        - AttributeName: connection-id
          KeyType: HASH
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: expiration-time

  GameStatesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: paper-tactics-game-states
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: expiration-time

  CreateGameRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: create-game
      AuthorizationType: NONE
      Target: !Join
        - /
        - - integrations
          - !Ref CreateGameIntegration

  CreateGameIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateGameFunction.Arn}/invocations

  CreateGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: paper-tactics-create-game
      Handler: create_game.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: paper-tactics-client-queue
        - DynamoDBCrudPolicy:
            TableName: paper-tactics-game-states
        - Statement:
          - Effect: Allow
            Action:
              - execute-api:ManageConnections
            Resource:
              - !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*

  CreateGamePermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebSocketApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CreateGameFunction
      Principal: apigateway.amazonaws.com

  MakeTurnRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: make-turn
      AuthorizationType: NONE
      Target: !Join
        - /
        - - integrations
          - !Ref MakeTurnIntegration

  MakeTurnIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MakeTurnFunction.Arn}/invocations

  MakeTurnFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: paper-tactics-make-turn
      Handler: make_turn.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: paper-tactics-game-states
        - Statement:
          - Effect: Allow
            Action:
              - execute-api:ManageConnections
            Resource:
              - !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*

  MakeTurnPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebSocketApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref MakeTurnFunction
      Principal: apigateway.amazonaws.com

Outputs:
  WebSocketURI:
    Value: !Join 
      - ''
      - - wss://
        - !Ref WebSocketApi
        - .execute-api.
        - !Ref AWS::Region
        - .amazonaws.com/
        - !Ref Stage
