name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: abatilo/actions-poetry@v2.1.3
      with:
        poetry-version: 1.1.11
    - run: poetry install
    - run: poetry run pre-commit run --all-files
    - run: poetry run sam build
      if: github.ref == 'refs/heads/master'
      working-directory: ./aws
    - run: poetry run sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
      if: github.ref == 'refs/heads/master'
      working-directory: ./aws
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
