name: poetry-dev

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: abatilo/actions-poetry@v2.1.3
      with:
        poetry-version: 1.1.11
    - run: poetry install
    - run: poetry run pre-commit run --all-files
